# Generated by Django 5.1.4 on 2024-12-06 00:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='tenant',
            name='date_of_lease',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='mobile',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='rank',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sector',
            field=models.CharField(choices=[('Police', 'Police'), ('Fire Dep', 'Fire Dep'), ('Drugs', 'Drugs')], default='Police', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_id',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='cluster',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='floors',
            field=models.CharField(choices=[('2', '2 floors'), ('3', '3 floors')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('Major', 'Major'), ('Minor', 'Minor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='villa',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
