# Generated by Django 5.1.4 on 2024-12-06 00:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_tenant_phone_number_tenant_date_of_lease_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('tenant_id', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('sector', models.CharField(blank=True, choices=[('Police', 'Police'), ('Fire Dep', 'Fire Dep'), ('Drugs', 'Drugs')], max_length=50, null=True)),
                ('date_of_lease', models.DateField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('cluster', models.CharField(blank=True, max_length=50, null=True)),
                ('villa', models.CharField(blank=True, max_length=50, null=True)),
                ('archived_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='cluster',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='floors',
            field=models.CharField(blank=True, choices=[('2', '2 floors'), ('3', '3 floors')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(blank=True, default='Vacant', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, choices=[('Major', 'Major'), ('Minor', 'Minor')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='villa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='date_of_lease',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='sector',
            field=models.CharField(blank=True, choices=[('Police', 'Police'), ('Fire Dep', 'Fire Dep'), ('Drugs', 'Drugs')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
