# Generated by Django 5.1.4 on 2024-12-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_delete_sectors_property_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, choices=[('للضباط', 'مخصصة للضباط'), ('للافراد', 'مخصصة للافراد')], max_length=50, null=True),
        ),
    ]
