# Generated by Django 5.1.4 on 2024-12-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_archivedtenant_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedtenant',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='archivedtenant',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='property',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='property',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
